# databricks/utils/delta_helpers.py
#
# Shared PySpark helpers used by the gold-layer processing jobs.
# These utilities handle Delta upserts, partition replacement,
# rolling-date calculations, and basic data-quality checks.
#
# Databricks notebook usage:
#   %run ./utils/delta_helpers
#
# Databricks Repos usage:
#   from utils.delta_helpers import merge_into_delta, rolling_window_filter

from datetime import date, timedelta

from pyspark.sql import DataFrame, SparkSession
from pyspark.sql import functions as F
from pyspark.sql.types import StringType


# ---------------------------------------------------------------------------
# Delta Lake operations
# ---------------------------------------------------------------------------

def merge_into_delta(
    spark: SparkSession,
    source_df: DataFrame,
    target_path: str,
    merge_keys: list,
    update_cols: list = None,
) -> dict:
    """
    Upsert records from source_df into a Delta table.

    A new Delta table is created when the target path does not exist.
    Otherwise, records are matched using merge_keys.

    Matched rows:
        Updated using update_cols, or all non-key columns when
        update_cols is not supplied.

    Unmatched rows:
        Inserted into the target table.

    Returns:
        Dictionary containing inserted, updated, and total row counts.
    """

    from delta.tables import DeltaTable

    # No existing Delta table: create it from the incoming data.
    if not DeltaTable.isDeltaTable(spark, target_path):
        (
            source_df.write
            .format("delta")
            .mode("overwrite")
            .save(target_path)
        )

        row_count = source_df.count()

        print(
            f"  Created Delta table: {target_path} "
            f"({row_count} rows)"
        )

        return {
            "inserted": row_count,
            "updated": 0,
            "total": row_count,
        }

    target_delta = DeltaTable.forPath(spark, target_path)

    # Construct the MERGE ON expression from the supplied key columns.
    join_expression = " AND ".join(
        f"target.{column} = source.{column}"
        for column in merge_keys
    )

    # When update columns are not specified, update every non-key field.
    columns_to_update = update_cols or [
        column
        for column in source_df.columns
        if column not in merge_keys
    ]

    update_values = {
        column: f"source.{column}"
        for column in columns_to_update
    }

    # Insert mapping contains every source column.
    insert_values = {
        column: f"source.{column}"
        for column in source_df.columns
    }

    (
        target_delta.alias("target")
        .merge(
            source_df.alias("source"),
            join_expression,
        )
        .whenMatchedUpdate(set=update_values)
        .whenNotMatchedInsert(values=insert_values)
        .execute()
    )

    # Read the metrics generated by the latest Delta operation.
    latest_metrics = (
        target_delta
        .history(1)
        .select("operationMetrics")
        .collect()[0][0]
    )

    rows_inserted = int(
        latest_metrics.get("numTargetRowsInserted", 0)
    )

    rows_updated = int(
        latest_metrics.get("numTargetRowsUpdated", 0)
    )

    print(
        f"  MERGE finished: {rows_inserted} inserted, "
        f"{rows_updated} updated -> {target_path}"
    )

    return {
        "inserted": rows_inserted,
        "updated": rows_updated,
        "total": rows_inserted + rows_updated,
    }


def overwrite_partition(
    df: DataFrame,
    target_path: str,
    partition_col: str,
    partition_value: str,
) -> int:
    """
    Replace one partition of a Delta table.

    REPLACE WHERE makes the operation idempotent: running the same
    partition again replaces that partition instead of creating
    duplicate records.

    Returns the number of rows written.
    """

    rows_to_write = df.count()

    (
        df.write
        .format("delta")
        .mode("overwrite")
        .option(
            "replaceWhere",
            f"{partition_col} = '{partition_value}'",
        )
        .save(target_path)
    )

    print(
        f"  Replaced {partition_col}={partition_value}: "
        f"{rows_to_write} rows -> {target_path}"
    )

    return rows_to_write


# ---------------------------------------------------------------------------
# Rolling-window utilities
# ---------------------------------------------------------------------------

def rolling_window_filter(
    df: DataFrame,
    date_col: str,
    run_date: date,
    window_days: int,
) -> DataFrame:
    """
    Select records belonging to the current rolling window.

    The run_date is included as the final day of the window.

    For example, with a seven-day window ending on 2024-01-15,
    the selected dates are 2024-01-09 through 2024-01-15.
    """

    start_date = (
        run_date - timedelta(days=window_days - 1)
    ).isoformat()

    end_date = run_date.isoformat()

    return df.filter(
        (F.col(date_col) >= start_date)
        & (F.col(date_col) <= end_date)
    )


def prior_window_filter(
    df: DataFrame,
    date_col: str,
    run_date: date,
    window_days: int,
) -> DataFrame:
    """
    Select the period immediately preceding the current rolling window.

    This is used when calculating trend values by comparing the current
    window with the previous window.
    """

    previous_end = (
        run_date - timedelta(days=window_days)
    ).isoformat()

    previous_start = (
        run_date - timedelta(days=(window_days * 2 - 1))
    ).isoformat()

    return df.filter(
        (F.col(date_col) >= previous_start)
        & (F.col(date_col) <= previous_end)
    )


# ---------------------------------------------------------------------------
# Data-quality checks
# ---------------------------------------------------------------------------

def assert_silver_schema(df: DataFrame) -> None:
    """
    Verify that the silver-layer DataFrame contains the fields required
    by the gold aggregation process.

    Raises ValueError when one or more required columns are absent.
    """

    required_columns = {
        "id",
        "category",
        "publishedAt",
        "nlpStatus",
        "sentiment",
        "entities",
        "keyPhrases",
    }

    available_columns = set(df.columns)
    missing_columns = required_columns - available_columns

    if missing_columns:
        raise ValueError(
            "Silver DataFrame is missing required columns: "
            f"{sorted(missing_columns)}. "
            f"Available columns: {sorted(available_columns)}"
        )

    print(
        f"  Silver schema check passed - "
        f"{len(available_columns)} columns available"
    )


def log_data_quality(
    df: DataFrame,
    label: str,
) -> None:
    """
    Print a compact quality summary for a DataFrame.

    Reports total rows, successful NLP rows, failed NLP rows,
    and PII rows when the hasPii column is available.
    """

    total_rows = df.count()

    successful_nlp = (
        df.filter(F.col("nlpStatus") == "ok")
        .count()
    )

    failed_nlp = total_rows - successful_nlp

    if "hasPii" in df.columns:
        pii_rows = (
            df.filter(F.col("hasPii") == True)
            .count()
        )
    else:
        pii_rows = "N/A"

    print(
        f"  [{label}] "
        f"rows={total_rows} "
        f"nlpOk={successful_nlp} "
        f"nlpFailed={failed_nlp} "
        f"pii={pii_rows}"
    )

    if total_rows == 0:
        print(
            f"  WARNING: [{label}] DataFrame contains no rows"
        )

    elif failed_nlp / max(total_rows, 1) > 0.20:
        print(
            f"  WARNING: [{label}] NLP failure rate exceeds 20% - "
            "check fn-enrich logs"
        )


def safe_explode_entities(df: DataFrame) -> DataFrame:
    """
    Expand the entities array into individual rows.

    The function supports both entity representations used by the
    pipeline:

      1. Structured entities from Azure Language:
         {text, category, confidenceScore}

      2. Simple string entities, such as those flattened for Search.

    The resulting DataFrame contains:
        id
        category
        entity_text
    """

    entity_schema = df.schema["entities"].dataType

    # Detect whether each entity is represented as a StructType.
    has_struct_entities = (
        hasattr(entity_schema, "elementType")
        and hasattr(entity_schema.elementType, "fields")
        and "text" in [
            field.name
            for field in entity_schema.elementType.fields
        ]
    )

    exploded_entities = (
        df.filter(F.col("entities").isNotNull())
        .select(
            "id",
            "category",
            F.explode("entities").alias("entity"),
        )
    )

    if has_struct_entities:
        return exploded_entities.withColumn(
            "entity_text",
            F.when(
                F.col("entity.text").isNotNull(),
                F.col("entity.text"),
            ).otherwise(
                F.col("entity").cast(StringType())
            ),
        )

    return exploded_entities.withColumn(
        "entity_text",
        F.col("entity").cast(StringType()),
    )