// storage.bicep
// Provisions the storage layer used throughout the NLP pipeline:
//
//   - Azure Storage Account with Blob, Table, and Queue services
//   - ADLS Gen2 filesystems for bronze, silver, gold, and error data
//   - Tables for deduplication and audit records
//   - Queue used for article enrichment
//   - Poison queue for failed enrichment messages
//   - Event Grid system topic for BlobCreated events
//
// Event Grid subscriptions are configured separately in eventgrid.bicep.

@description('Azure deployment region')
param location string = resourceGroup().location

@description('Globally unique storage account name (3-24 lowercase alphanumeric characters)')
param storageAccountName string

@description('Common tags applied to storage resources')
param tags object = {
  project: 'news-nlp'
  layer: 'storage'
  managedBy: 'bicep'
}

// ── Storage account ───────────────────────────────────────────────────────────
// Hierarchical namespace enables ADLS Gen2 functionality.

resource dataStorage 'Microsoft.Storage/storageAccounts@2023-01-01' = {
  name: storageAccountName
  location: location
  tags: tags
  kind: 'StorageV2'

  sku: {
    name: 'Standard_LRS'
  }

  properties: {
    isHnsEnabled: true
    supportsHttpsTrafficOnly: true
    minimumTlsVersion: 'TLS1_2'
    allowBlobPublicAccess: false

    networkAcls: {
      // Restrict this further to a VNet/private endpoint for production.
      defaultAction: 'Allow'
    }
  }
}

// ── Blob service ──────────────────────────────────────────────────────────────

resource blobStorageService 'Microsoft.Storage/storageAccounts/blobServices@2023-01-01' = {
  parent: dataStorage
  name: 'default'

  properties: {
    deleteRetentionPolicy: {
      enabled: true
      days: 7
    }
  }
}

// ── ADLS Gen2 containers ──────────────────────────────────────────────────────

var dataContainers = [
  {
    name: 'articles-bronze'
    comment: 'Raw NewsAPI article JSON written during ingestion'
  }
  {
    name: 'articles-silver'
    comment: 'NLP-enriched article documents produced by fn-enrich'
  }
  {
    name: 'articles-gold'
    comment: 'Aggregated analytics generated by Databricks'
  }
  {
    name: 'articles-error'
    comment: 'Articles that failed enrichment and require inspection'
  }
]

resource pipelineContainers 'Microsoft.Storage/storageAccounts/blobServices/containers@2023-01-01' = [
  for container in dataContainers: {
    parent: blobStorageService
    name: container.name

    properties: {
      publicAccess: 'None'
    }
  }
]

// ── Table storage ─────────────────────────────────────────────────────────────

resource tableStorageService 'Microsoft.Storage/storageAccounts/tableServices@2023-01-01' = {
  parent: dataStorage
  name: 'default'
}

resource articleDedupTable 'Microsoft.Storage/storageAccounts/tableServices/tables@2023-01-01' = {
  parent: tableStorageService
  name: 'articleDedup'
}

resource articleAuditTable 'Microsoft.Storage/storageAccounts/tableServices/tables@2023-01-01' = {
  parent: tableStorageService
  name: 'articleAudit'
}

// ── Queue storage ─────────────────────────────────────────────────────────────

resource queueStorageService 'Microsoft.Storage/storageAccounts/queueServices@2023-01-01' = {
  parent: dataStorage
  name: 'default'
}

resource articleEnrichmentQueue 'Microsoft.Storage/storageAccounts/queueServices/queues@2023-01-01' = {
  parent: queueStorageService
  name: 'article-enrich-queue'

  properties: {
    metadata: {}
  }
}

// Explicit poison queue declaration.
// Azure Storage Queue processing also uses the "-poison" naming convention
// when messages exceed the configured dequeue limit.

resource enrichmentPoisonQueue 'Microsoft.Storage/storageAccounts/queueServices/queues@2023-01-01' = {
  parent: queueStorageService
  name: 'article-enrich-queue-poison'

  properties: {
    metadata: {}
  }
}

// ── Event Grid system topic ───────────────────────────────────────────────────
// The topic receives BlobCreated events from the storage account.
// Event subscriptions are defined in eventgrid.bicep.

resource storageEventTopic 'Microsoft.EventGrid/systemTopics@2022-06-15' = {
  name: '${storageAccountName}-events'
  location: location
  tags: tags

  properties: {
    source: dataStorage.id
    topicType: 'Microsoft.Storage.StorageAccounts'
  }
}

// ── Deployment outputs ────────────────────────────────────────────────────────

@description('Storage account name used by the Logic App')
output storageAccountName string = dataStorage.name

@description('Storage account resource ID used for Purview role assignments')
output storageAccountResourceId string = dataStorage.id

@description('Primary Blob service endpoint')
output blobEndpoint string = dataStorage.properties.primaryEndpoints.blob

@description('Primary ADLS Gen2 DFS endpoint')
output dfsEndpoint string = dataStorage.properties.primaryEndpoints.dfs

@description('Event Grid system topic name used by eventgrid.bicep')
output eventGridTopicName string = storageEventTopic.name

@description('Storage connection string; store securely rather than committing it to source control')
output storageConnectionString string = 'DefaultEndpointsProtocol=https;AccountName=${dataStorage.name};AccountKey=${dataStorage.listKeys().keys[0].value};EndpointSuffix=core.windows.net'